package org.kindredhq.discussions.core.domain.ids

import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Utility for generating discussion identifiers.
 *
 * This object provides a default UUID generation strategy for
 * discussion entities. Identity is domain-owned and may be
 * generated by the creating service prior to persistence.
 *
 * Implementing services are not required to use this generator.
 * Alternative ID strategies (e.g., ULID, database-generated UUIDs,
 * deterministic IDs for testing) may be used if desired.
 *
 * This utility exists to centralize identity generation and
 * maintain consistency across implementations.
 */
@OptIn(ExperimentalUuidApi::class)
public object DiscussionIds {
    /**
     * Generates a new random [Uuid] for a discussion entity.
     */
    public fun newId(): Uuid = Uuid.random()
}
