package org.kindredhq.discussions.core.domain.model

import org.kindredhq.discussions.core.domain.enums.DiscussionsStatus
import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.Serializable

/**
 * Represents a single discussion entry within a threaded discussion.
 *
 * A [Discussion] may represent either:
 * - A top-level post (when [parentId] is `null`)
 * - A comment replying to another discussion (when [parentId] is not `null`)
 *
 * Identity is generated by the discussion domain utilities and supplied by the creating service.
 * This model is persistence-agnostic and contains no infrastructure concerns.
 *
 * ### Threading Model
 * Thread hierarchy is determined solely by [parentId].
 * A `null` parent indicates a root-level post.
 *
 * ### Moderation Model
 * Visibility and moderation state are controlled through [status].
 * Derived properties such as [isDeleted], [isHidden], and [isVisible]
 * provide convenience accessors for common state checks.
 *
 * ### Reporting Model
 * [reportedBy] contains the set of user IDs that have reported this discussion.
 * Deduplication is enforced by using a [Set].
 *
 * @property id Unique identifier for this discussion entry.
 * @property targetId Optional identifier of the external entity this discussion is associated with.
 *                     This value is not owned or generated by the discussion domain.
 * @property parentId Identifier of the parent discussion if this is a comment.
 * @property userId Identifier of the user who created this discussion entry.
 * @property body Text body of the discussion entry. Length constraints are enforced by validation logic.
 * @property language Optional BCP 47 language tag associated with the discussion content.
 *                    Interpretation and validation are implementation-defined.
 *
 * @property status Moderation and visibility state.
 * @property reason Optional moderation reason or explanatory note.
 * @property moderatedBy Identifier of the moderator who performed an action.
 * @property moderatedAt Timestamp of the most recent moderation action.
 *
 * @property reportedBy Set of user identifiers who have reported this discussion.
 *
 * @property isPinned Indicates whether this discussion is pinned within its context.
 * @property isLocked Indicates whether replies are disabled.
 *
 * @property createdAt Timestamp when the discussion was created.
 * @property updatedAt Timestamp of the most recent content update.
 * @property deletedAt Timestamp when the discussion was deleted, if applicable.
 * @property purgeAt Timestamp indicating when the discussion is eligible for permanent removal.
 */
@Serializable
@OptIn(ExperimentalUuidApi::class)
data class Discussion(
    val id: Uuid,
    val targetId: Uuid? = null,
    val parentId: Uuid? = null,
    val userId: String,
    val body: String,
    val language: String? = null,
    // Moderation
    val status: DiscussionsStatus = DiscussionsStatus.VISIBLE,
    val reason: String? = null,
    val moderatedBy: String? = null,
    val moderatedAt: Instant? = null,
    // Reporting
    val reportedBy: Set<String> = emptySet(),
    // Admin
    val isPinned: Boolean = false,
    val isLocked: Boolean = false,
    val createdAt: Instant,
    val updatedAt: Instant? = null,
    val deletedAt: Instant? = null,
    val purgeAt: Instant? = null,
) {
    override fun toString(): String =
        "Discussion(" +
            "id='$id', " +
            "targetId=$targetId, " +
            "parentId=$parentId, " +
            "userId='$userId', " +
            "body='${body.take(20)}...', " +
            "lang='$language', " +
            "status=$status, " +
            "createdAt=$createdAt" +
            ")"

    val isDeleted: Boolean
        get() =
            status == DiscussionsStatus.DELETED_BY_AUTHOR ||
                status == DiscussionsStatus.DELETED_BY_MODERATOR

    val isHidden: Boolean
        get() =
            status == DiscussionsStatus.HIDDEN_BY_REPORTS ||
                status == DiscussionsStatus.HIDDEN_BY_MODERATOR ||
                isDeleted

    val isVisible: Boolean
        get() = !isHidden
}
